name: Test custom action

on:
  push:
    branches: [custom-action]

jobs:
  test-custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: ./.github/actions/esp-build
